loader:
  ehr: 100
  composition-per-ehr: 200
spring:
  datasource:
    url: @db.url@
    username: @db.username@
    password: @db.password@
    driver-class-name: @db.driver@
    hikari:
      maximum-pool-size: 20
  main:
    web-application-type: none
logging:
  level:
    com.zaxxer.hikari: warn
    org.jooq: warn
