loader:
  ehr: 100
  composition-per-ehr: 200
spring:
  datasource:
    url: jdbc:yugabytedb://10.216.24.69:5433/ehrbase?load-balance=true
    username: ehrbase
    password: ehrbase
    driver-class-name: com.yugabyte.Driver
    hikari:
      maximum-pool-size: 20
  main:
    web-application-type: none
logging:
  level:
    com.zaxxer.hikari: warn
    org.jooq: warn
